name: TapLMoon
version: ${project.version}
main: dev.barfuzzle99.taplmoon.taplmoon.TaplMoon
api-version: 1.16
load: POSTWORLD
depend:
  - AdvancedWorldCreatorAPI
commands:
  taplmoon:
    description: Main command for the TapLMoon plugin